$(document).ready(function () {
    $("#a").mouseenter(function(){
        $(this).fadeTo(1000,0.5);
    });
    $("#a").mouseleave(function(){
       $(this).fadeTo(1000,1);
    });
    $("#b").mouseenter(function(){
        $(this).fadeTo(1000,0.5);
    });
    $("#b").mouseleave(function(){
        $(this).fadeTo(1000,1);
    });
    $("#c").mouseenter(function(){
        $(this).fadeTo(1000,0.5);
    });
    $("#c").mouseleave(function(){
        $(this).fadeTo(1000,1);
    });
    $("#d").mouseenter(function(){
        $(this).fadeTo(1000,0.5);
    });
    $("#d").mouseleave(function(){
        $(this).fadeTo(1000,1);
    });
    $("#e").mouseenter(function(){
        $(this).fadeTo(1000,0.5);
    });
    $("#e").mouseleave(function(){
        $(this).fadeTo(1000,1);
    });
    $("#f").mouseenter(function(){
        $(this).fadeTo(1000,0.5);
    });
    $("#f").mouseleave(function(){
        $(this).fadeTo(1000,1);
    });
    $("#g").mouseenter(function(){
        $(this).fadeTo(1000,0.5);
    });
    $("#g").mouseleave(function(){
        $(this).fadeTo(1000,1);
    });
    $("#h").mouseenter(function(){
        $(this).fadeTo(1000,0.5);
    });
    $("#h").mouseleave(function(){
        $(this).fadeTo(1000,1);
    });
});

